apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deply
    labels:
        app: dev
        vani: test
spec:
    replicas: 3
    selector:
      matchLabels:
          app: dev
          vani: test
    template:
        metadata:
            name: my-deply-pod
            labels:
                app: dev
                vani: test
        spec:
            containers:
                - name: test-cont
                  image: gulshan845401/test
